backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "content"
    label: "Website Content"
    files:
      - file: "data.json"
        label: "Home Page Text"
        name: "home"
        fields:
          - {label: "Our Purpose", name: "about_text", widget: "text"}
          - {label: "Community Day Intro", name: "community_text", widget: "text"}
          - {label: "Studio Hire Teaser", name: "studio_teaser", widget: "text"}
          - {label: "Workshops Intro", name: "workshops_header", widget: "text"}
          - {label: "Newsletter Intro", name: "newsletters_intro", widget: "text"}
          # Inside admin/config.yml under 'fields'
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "string"}